adfinis/mySAGW

.github/workflows/tests.yml
.pre-commit-config.yaml
Makefile
caluma/Dockerfile
caluma/ci/test.sh
caluma/extensions/permissions.py
caluma/extensions/tests/test_permissions.py
caluma/extensions/tests/test_visibilities.py
caluma/extensions/visibilities.py
caluma/setup.cfg
docker-compose.override.yml
docker-compose.yml
postgres/init-db.sh
proxy/nginx.conf

This commit introduces the Caluma service. It also introduces an nginx
proxy for routing the requests.

feat: introduce Caluma service

---

README.md
keycloak/dev-config.json

This commit
- adds groups to the keycloak config
- adds mysagw.local:4200 to redirect_uris in keycloak config
- documents how to get started for development

chore: extend keycloak config

---

.envs/.local/.keycloak
.envs/.production.example/.keycloak
.envs/.production.example/.mail
docker-compose.override.yml
docker-compose.prod.yml
docker-compose.staging.yml
docker-compose.yml
keycloak/dev-config.json

feat: add mailing containers for sending mail

---

api/mysagw/oidc_auth/authentication.py
api/mysagw/oidc_auth/models.py
api/mysagw/oidc_auth/tests/test_authentication.py

This commit fixes a hen/egg-problem when managing Identities during
auth.
Additionally it falls back on idp_id matchinf, if multiple Identites
have been found.

fix(api): fix identity handling in auth

---

api/mysagw/identity/filters.py
api/mysagw/identity/tests/test_email_views.py
api/mysagw/identity/tests/test_identity_views.py
api/mysagw/identity/views.py

This commit adds following filters:
- identites: `is-organisation`
- additional-emails: `identity`
- phone-numbers: `identity`
- memberships: `identity`

feat: add needed filters to the views

---

ember/app/ui/identities/index/controller.js
ember/mirage/config.js

The total amount of pages is currently `totalPages` but should just
be `pages`. This also adds the other meta information.

fix(ember): correct pagination data used for component

---

ember/app/ui/components/identity-form/component.js
ember/app/ui/components/identity-form/template.hbs
ember/app/validations/identity.js

The field was shown but didn't do anything.

fix(ember): connect email field correctly to the changeset

---

ember/app/services/notification.js
ember/app/ui/components/identity-emails/component.js
ember/app/ui/components/identity-form/component.js
ember/app/ui/components/identity-interests/component.js
ember/app/ui/components/identity-memberships/component.js
ember/app/ui/components/identity-phone-numbers/component.js
ember/app/ui/components/interest-category-form/component.js
ember/app/ui/identities/index/controller.js
ember/app/ui/interests/edit/controller.js
ember/app/ui/interests/index/controller.js
ember/app/utils/apply-error.js
ember/app/utils/format-error.js
ember/tests/unit/services/notification-test.js
ember/tests/unit/utils/apply-error-test.js
ember/tests/unit/utils/format-error-test.js

Only show error messages and add errors to changeset where applicable.

feat(ember): update error handling

---

ember/app/ui/identities/index/controller.js
ember/mirage/config.js

fix(ember): correct property path in JSON:API meta

---

docker-compose.yml
ember/app/ui/components/identity-form/component.js

And fix direct link to user in keycloak.

Upgrade keycloak

---

ember/app/validations/email.js
ember/app/validations/identity.js

As is the case on the API side.

fix(ember): update identity validations to make email optional

---

api/mysagw/identity/views.py

This line was removed during the recent merges.

chore: reimport ValidationError

---

ember/app/router.js
ember/app/ui/index/route.js
ember/tests/unit/ui/index/route-test.js

Redirect from home to the cases route.

feat(ember): add index route

---

ember/app/ui/components/identity-form/component.js
ember/app/ui/components/identity-form/template.hbs
ember/app/ui/identities/edit/controller.js
ember/app/ui/identities/edit/template.hbs
ember/tests/unit/ui/identities/edit/controller-test.js

Organisations cannot be nested.

fix(ember): don't let organisations manage memberships

---

ember/app/ui/identities/index/controller.js
ember/app/ui/identities/index/template.hbs
ember/package.json
ember/translations/en.yaml
ember/yarn.lock

Export the current search as XLS.

feat(ember): add export to identity search/list.

---

ember/app/models/identity.js
ember/app/ui/components/identity-form/component.js
ember/app/ui/components/identity-form/template.hbs
ember/app/ui/identities/index/template.hbs
ember/translations/en.yaml

feat(ember): add salutation to identity

---

ember/app/ui/components/identity-phone-numbers/template.hbs

Add check to see if the default phone number is also the last
which makes it deletable.

fix(ember): make last number deletable

---

ember/app/ui/components/identity-phone-numbers/template.hbs
ember/translations/en.yaml

One missed replacement and a plural where none should be.

fix(ember): correct mistakes made while copy/pasting code

---

ember/app/abilities/address.js
ember/app/models/address.js
ember/app/ui/components/identity-addresses/component.js
ember/app/ui/components/identity-addresses/template.hbs
ember/app/ui/identities/edit/template.hbs
ember/app/validations/address.js
ember/mirage/config.js
ember/mirage/factories/address.js
ember/mirage/factories/identity.js
ember/tests/integration/ui/components/identity-address/component-test.js
ember/translations/en.yaml
ember/yarn.lock

Depends on https://github.com/adfinis-sygroup/mySAGW/pull/126

feat(ember): add address management

---

ember/app/models/membership.js
ember/app/ui/components/identity-memberships/template.hbs
ember/translations/en.yaml

Also handle make them visible in the list view.
Additional fix:
- fix(ember): wait for correct fetch operation

feat(ember): handle `authorized` and `inactive` on memberships

---

ember/package.json
ember/yarn.lock

See previous commit 85840d10988a27f38e58c82d7b793db2d865eed6

update ember validated form

---

api/mysagw/identity/filters.py
ember/app/styles/app.scss
ember/app/ui/components/identity-members/component.js
ember/app/ui/components/identity-members/template.hbs
ember/app/ui/components/identity-memberships/template.hbs
ember/app/ui/identities/edit/template.hbs
ember/tests/integration/ui/components/identity-members/component-test.js
ember/translations/en.yaml

feat(ember): add members list to organisation view

---

ember/app/ui/components/identity-form/component.js
ember/app/ui/components/identity-form/template.hbs
ember/app/ui/components/identity-interests/component.js
ember/app/ui/components/identity-interests/template.hbs
ember/app/ui/components/identity-memberships/component.js
ember/app/ui/components/identity-memberships/template.hbs
ember/translations/en.yaml

allow tabbing with selects
add save and back button to identity

feat(ember): improve identity editing

---

ember/Dockerfile
ember/config/deploy.js
ember/package.json
ember/yarn.lock

fix(docker): use ember-cli as base image for frontend build

---

ember/app/caluma-query/models/work-item.js
ember/app/gql/queries/get-case.graphql
ember/app/gql/queries/get-cases.graphql
ember/app/ui/cases/detail/index/template.hbs
ember/app/ui/components/dynamic-table/table-data/template.hbs
ember/app/ui/components/work-item-list/item/template.hbs
ember/app/ui/work-items/controller.js
ember/config/environment.js
ember/translations/en.yaml

feat(ember): show document numbers 

---

caluma/extensions/events/work_item.py
caluma/extensions/settings.py
caluma/extensions/tests/test_events.py

feat(caluma): also send notification mail before complete-document

feat(caluma): set cases status

---

caluma/extensions/settings.py
caluma/extensions/tests/test_events.py
ember/.eslintignore
ember/app/caluma-query/models/work-item.js
ember/app/gql/queries/get-case.graphql
ember/app/gql/queries/get-cases.graphql
ember/app/styles/components/work-item-list/index.scss
ember/app/ui/cases/detail/circulation/route.js
ember/app/ui/cases/detail/index/controller.js
ember/app/ui/cases/detail/index/template.hbs
ember/app/ui/components/cases-table/component.js
ember/app/ui/components/dynamic-table/answer-value/component.js
ember/app/ui/components/dynamic-table/answer-value/template.hbs
ember/app/ui/components/dynamic-table/case-created-by/component.js
ember/app/ui/components/dynamic-table/case-created-by/template.hbs
ember/app/ui/components/dynamic-table/case-user/component.js
ember/app/ui/components/dynamic-table/case-user/template.hbs
ember/app/ui/components/dynamic-table/date/template.hbs
ember/app/ui/components/dynamic-table/table-data/component.js
ember/app/ui/components/dynamic-table/table-data/template.hbs
ember/app/ui/components/identity-form/template.hbs
ember/app/ui/components/nav-bar/template.hbs
ember/app/ui/components/work-item-list/item/component.js
ember/app/ui/components/work-item-list/item/template.hbs
ember/app/ui/components/work-item-list/template.hbs
ember/app/ui/profile/index/template.hbs
ember/app/ui/work-items/controller.js
ember/config/environment.js
ember/translations/en.yaml
ember/yarn.lock

display case meta status and createdbyuser in casetable
fix first circulation bug
fix mobile nav bug
improve workitemlist ui, show deadline color next to task name

fix(ember): various improvements and bug fixes

---

ember/app/caluma-query/models/form.js
ember/app/ui/cases/new/controller.js
ember/app/ui/cases/new/route.js
ember/app/ui/cases/new/template.hbs

Load organisation correctly, to avoid missing filters
Sort forms by advisory board and expert association

fix(ember): fix problems with new case view

---

ember/app/app.js
ember/app/models/identity.js
ember/app/ui/components/identity-interests/component.js
ember/app/ui/components/identity-interests/template.hbs
ember/app/ui/identities/edit/template.hbs

fix(ember): display category in interest list after reload

---

caluma/data/workflow-config.json
caluma/extensions/dynamic_tasks.py
caluma/extensions/events/work_item.py
caluma/extensions/settings.py
caluma/extensions/tests/test_dynamic_tasks.py
caluma/extensions/tests/test_events.py
ember/app/caluma-query/models/work-item.js
ember/app/ui/cases/detail/work-items/edit/form/controller.js
ember/app/ui/cases/detail/work-items/edit/form/route.js
ember/app/ui/cases/detail/work-items/edit/form/template.hbs
ember/app/ui/cases/detail/work-items/index/controller.js
ember/app/ui/components/nav-bar/template.hbs

approved in #390 
no changes were added

Fix additional data

---

ember/app/ui/cases/detail/index/controller.js
ember/app/ui/components/dynamic-table/case-access-actions/component.js

fix deleting invitation
fix duplicate email check

fix(ember): fix problems with access table

---

Makefile
caluma/Dockerfile
docker-compose.yml

beta.4 should be a broken image with the underlying python image is
broken

chore: upgrade caluma image

---

ember/package.json
ember/yarn.lock

Cherry picked `ember-pikaday` update

Next staging release

---

api/mysagw/identity/filters.py
api/mysagw/identity/views.py
ember/app/abilities/-base.js
ember/app/abilities/identity.js
ember/app/ui/components/identity-addresses/template.hbs
ember/app/ui/components/identity-emails/template.hbs
ember/app/ui/components/identity-form/component.js
ember/app/ui/components/identity-form/template.hbs
ember/app/ui/components/identity-interests/template.hbs
ember/app/ui/components/identity-phone-numbers/template.hbs
ember/app/ui/profile/edit/template.hbs
ember/translations/profile/de.yaml
ember/translations/profile/en.yaml
ember/translations/profile/fr.yaml

Revert "fix(ember): allow org admins to edit org through profile"
This reverts commit a6bb8fb0e287897022517e1a5e9a2e76915300e0.

fix(ember): revert org admin editing through profile

---

api/mysagw/identity/views.py

fix(api): add missing search to public identity view

---

ember/app/ui/components/submit-button/component.js

fix forgotten conditional form https://github.com/adfinis/mySAGW/pull/589

fix(ember): change submit disabled condition

---

ember/app/gql/queries/get-case.graphql
ember/app/ui/cases/index/controller.js
ember/app/ui/cases/index/route.js
ember/app/ui/cases/index/template.hbs
ember/app/ui/components/cases-table/component.js
ember/app/ui/components/cases-table/template.hbs
ember/app/ui/components/dynamic-table/component.js
ember/app/ui/components/dynamic-table/template.hbs
ember/config/environment.js
ember/translations/documents/de.yaml
ember/translations/documents/en.yaml
ember/translations/documents/fr.yaml

New ordering

---

ember/app/ui/cases/index/controller.js
ember/app/ui/cases/index/template.hbs
ember/app/ui/components/cases-table/component.js
ember/app/ui/components/cases-table/template.hbs
ember/app/ui/components/dynamic-table/template.hbs

fix(ember): fix identity filter

---

ember/app/caluma-query/models/case.js
ember/app/styles/app.scss
ember/app/ui/cases/index/controller.js
ember/app/ui/cases/index/route.js
ember/app/ui/components/cases-table/component.js
ember/app/ui/components/filters/dropdown/component.js
ember/app/ui/components/filters/dropdown/template.hbs
ember/app/ui/components/filters/input/template.hbs

remove two way binding to debounce inputs
call case-access with query parameters
add answer search to query parameters

fix(ember): qol improvements for case filtering

---

caluma/Dockerfile
docker-compose.yml
ember/app/ui/components/nav-bar/template.hbs
ember/config/environment.js
ember/package.json
ember/yarn.lock

upgrade major versions manually

fix(ember): remove unnecessary dependency

---

ember/app/caluma-query/models/work-item.js
ember/app/services/apollo.js
ember/app/ui/cases/index/controller.js
ember/app/ui/cases/index/route.js
ember/app/ui/cases/index/template.hbs
ember/app/ui/components/cases-table/template.hbs
ember/app/ui/components/dynamic-table/component.js
ember/app/ui/components/filters/identity/component.js
ember/app/ui/components/filters/identity/template.hbs
ember/app/ui/components/filters/template.hbs
ember/app/ui/components/work-item-list/template.hbs
ember/app/ui/work-items/controller.js
ember/app/ui/work-items/route.js
ember/app/ui/work-items/template.hbs
ember/config/environment.js

Fix bug with identity filter
Extract identity filter to component
Add ordering and new filters to work item list

feat(ember): add ordering and filters to work item list

---

api/mysagw/accounting/conftest.py
api/mysagw/accounting/queries/get_receipts.gql
api/mysagw/accounting/views.py
api/mysagw/case/application_parser.py
api/mysagw/case/queries/get_document.gql
api/mysagw/case/tests/application_caluma_response.py
api/mysagw/case/tests/snapshots/snap_test_case_views.py
api/mysagw/case/views.py
api/mysagw/pdf_utils.py

Drive-by commits:
* feat: add verteilplan to PDF export
* feat(PDF): add title to dossier_nr

fix(accounting): only download files needed for merge

---

ember/app/gql/queries/get-work-item-details.graphql
ember/app/gql/queries/get-work-items.graphql
ember/app/ui/cases/detail/index/controller.js
ember/app/ui/cases/detail/index/template.hbs
ember/app/ui/cases/detail/work-items/edit/form/controller.js
ember/app/ui/cases/detail/work-items/edit/form/route.js
ember/translations/work-items/de.yaml
ember/translations/work-items/en.yaml
ember/translations/work-items/fr.yaml

Workflow might will be stuck when additional-data-form is misssing, now a message will be displayed, to hint at a redo to be able to continue the case

feat(ember): add remark when additional-data is alone

---

ember/app/ui/cases/detail/download/controller.js
ember/app/ui/cases/detail/index/controller.js
ember/app/ui/work-items/controller.js
ember/app/ui/work-items/template.hbs
ember/app/utils/download-file.js
ember/translations/documents/de.yaml
ember/translations/documents/en.yaml
ember/translations/documents/fr.yaml

change export accounting file name to take it from the backend

fix(ember): add back work item responsible filter

---

api/mysagw/identity/management/commands/upload_template.py
api/setup.cfg

Plus `chore: enable warnings when running pytest`.

fix(upload_templates): make sure file is closed after upload

---

api/Dockerfile
caluma/Dockerfile
docker-compose.yml

Drive-by commit: chore: reduce RUN instructions in API Dockerfile

chore: update caluma to v8.0.0-beta.25

---

ember/app/ui/components/identity-addresses/template.hbs
ember/app/ui/components/identity-emails/template.hbs
ember/app/ui/components/identity-phone-numbers/template.hbs
ember/app/ui/components/interest-category-form/template.hbs
ember/app/ui/components/membership-role-form/template.hbs
ember/app/ui/components/snippet-form/template.hbs
ember/app/ui/interests/edit/template.hbs
ember/app/validations/interest-category.js
ember/app/validations/interest.js
ember/app/validations/membership-role.js

Fixes references for ember-localized-model v2

fix(ember): use _attribute for raw localized attribute access

---

Makefile
README.md

`chore: add analytics tables to caluma-dump-forms make target`

docs: update installation instructions and fix old links

---

ember/package.json
ember/yarn.lock

upgrade ember-data to fix a problem with ember-concurrency https://github.com/machty/ember-concurrency/issues/509

fix(ember): fix problem with ember-concurrency

---

api/mysagw/case/queries/get_credit_approval.gql
caluma/data/form-config.json
caluma/extensions/tests/__snapshots__/test_events.ambr
caluma/extensions/tests/test_events.py
next_deployment.md

The number format in the emails is broken now. Will be fixed with [this PR](https://github.com/adfinis/mySAGW/pull/771).

feat: convert question `gesprochener-rahmenkredit` to float

---

caluma/Dockerfile
docker-compose.yml

This will enable support word combinations in `SearchAnswersFilter`.

chore: update caluma

---

caluma/extensions/events/work_item.py
caluma/extensions/permissions.py
caluma/extensions/settings.py
caluma/extensions/tests/test_events.py
caluma/extensions/tests/test_permissions.py

`fix(caluma): also set case status on reopen_case`

fix(caluma): restrict reopen_case and redo_work_item

---

caluma/Dockerfile
caluma/extensions/email_texts/email_rejection.py
caluma/extensions/tests/__snapshots__/test_events.ambr
docker-compose.yml

fix: fix copy/paste mistake in mail text

---

caluma/extensions/common.py
caluma/extensions/visibilities.py

Rather a bandaid commit, in order to improve performance fast. Especially for admins.

fix(caluma): Improve performance in visibilities

---

api/mysagw/identity/views.py
next_deployment.md

* `chore: clear next_deployment.md`

feat: do not include interest description in identity search

---

ember/app/caluma-query/models/case.js
ember/app/gql/queries/get-case.graphql
ember/app/ui/cases/detail/index/template.hbs
ember/translations/documents/de.yaml
ember/translations/documents/en.yaml
ember/translations/documents/fr.yaml

rmeove description for verteilplan
add submit date
reorder information aswell
Before

feat(ember): change case detail info

---

caluma/extensions/tests/__snapshots__/test_visibilities.ambr
caluma/extensions/tests/test_visibilities.py
caluma/extensions/visibilities.py
ember/app/ui/cases/detail/index/controller.js

This fixes a bug with NWP not being able to access the case and work item list.

fix(circulation): fix work item list and case detail for circulation

---

ember/app/ui/components/dynamic-table/answer-value/component.js

prevents error when a required choice question was is hidden

fix(ember): check if answer has a value

---

api/Dockerfile
caluma/Dockerfile

Additionally add a TODO to the Caluma Dockerfile.

fix(docker): install dependencies as mysagw user

---

ember/app/abilities/case.js
ember/app/styles/app.scss
ember/app/ui/cases/detail/circulation/controller.js
ember/app/ui/cases/detail/work-items/index/controller.js
ember/app/ui/cases/index/controller.js
ember/app/ui/cases/index/template.hbs
ember/app/ui/components/case-access-tables/component.js
ember/app/ui/components/case-transfer/component.js
ember/app/ui/components/case-transfer/template.hbs
ember/app/ui/components/cases-table/component.js
ember/app/ui/components/cases-table/template.hbs
ember/app/ui/components/dynamic-table/checkbox/component.js
ember/app/ui/components/dynamic-table/checkbox/template.hbs
ember/app/ui/components/dynamic-table/header/template.hbs
ember/app/ui/components/dynamic-table/template.hbs
ember/app/ui/components/filters/identity/component.js
ember/app/ui/work-items/controller.js
ember/ember-cli-build.js
ember/translations/documents/de.yaml
ember/translations/work-items/de.yaml

Edit mode button
Edit mode active with a few selections
Transfer modal

feat(ember): add transfer

---

api/mysagw/caluma_document_parser.py

Some PDFs seem to have broken annotations. This leads to a TypeError,
that wasn't handeled. The merging still happens, if this error occurs, but some
annotations will be dropped (links visible, but not clickable).
In order to still properly handle the indexing in the form, some refactoring was
needed.

fix(api): handle TypeErrors when merging PDFs

---

ember/package.json
ember/yarn.lock

closes https://github.com/adfinis/mySAGW/pull/1170

chore(ember): update ember caluma

---

api/mysagw/healthz/health_checks.py
api/mysagw/healthz/tests/test_healthz.py
api/pyproject.toml
compose.yaml

This PR also will trigger a release.

fix(healthz): do not rely on SAGW email set on identity

---

caluma/Dockerfile

this should improve what trivy finds :)

chore(caluma): run apt upgrade

---

caddy/Caddyfile
compose.yaml
next_deployment.md

This commit upgrades Caddy, DMS and MinIO.

chore: upgrade components

---

ember/app/gql/queries/get-case.graphql

Fetching the answer data to display was forgotten

fix(ember): show decision-and-credit remark

---

compose.yaml
ember/app/styles/app.scss
ember/app/ui/cases/detail/index/template.hbs
ember/package.json

Drive-by:
* chore: trigger FE release

fix: hyphenate labels in overview table
