adfinis/mySAGW

- .pre-commit-config.yaml
- api/mysagw/identity/factories.py
- api/mysagw/identity/serializers.py
- api/mysagw/identity/tests/test_email_views.py
- api/mysagw/identity/tests/test_identity_views.py
- api/mysagw/oidc_auth/authentication.py
- api/mysagw/oidc_auth/models.py
**fix(api): fix IdentitySerializer**
This commit makes following changes to the IdentitySerializer:
- add field `is_organisation`
- add field `organisation_name`
- make idp_id read_only
**chore: fix black pre-commit-hook**
**chore(api): ignore InsecureRequestWarning in dev**
**fix(api): fix additional-emails resource_name**
**fix(api): set modified and created on identity creation**
**fix(api): add validation for setting "is_organisation"**
> Small fixes

- ember/app/ui/identities/index/template.hbs
Optional values mean that we otherwise don't see some identities
in the list as they come out as empty links.
> fix(ember): show more information on identity list

- ember/app/ui/components/identity-interests/component.js
- ember/app/ui/components/identity-interests/template.hbs
It only serves to confuse users.
> feat(ember): remove edit functionality from interests

- ember/app/ui/identities/index/template.hbs
This change forces all email addresses below the names for mobile
views and only wraps single addresses if the name or address are
too long.
> feat(ember): improve responsive layout for identities list

- ember/app/ui/identities/index/template.hbs
- ember/app/ui/interests/index/template.hbs
They get lost at the bottom of the list and FABs don't work with
UIkit.
> feat(ember): move add buttons to the top (heading)

- ember/mirage/factories/identity.js
- ember/mirage/scenarios/default.js
- ember/tests/integration/ui/components/identity-emails/component-test.js
- ember/tests/integration/ui/components/identity-phone-numbers/component-test.js
What's not created automatically is lost on page refresh / code change.
> feat(ember): update identity factory to include interests

- ember/app/ui/components/identity-phone-numbers/component.js
This is an artifact from copy/pasting the email address component.
> fix(ember): set correct key in translation options

- ember/translations/en.yaml
I forgot to remove them when I removed the accociated functionality.
> fix(ember): remove obsolete translations

- ember/app/ui/components/identity-form/component.js
- ember/app/ui/components/identity-form/template.hbs
- ember/translations/en.yaml
All other entities can be deleted from their list views while the
identity list will have enough bells and whistles already.
> feat(ember): add delete function to identitiy form

- ember/app/ui/components/identity-form/template.hbs
Otherwise, it looks broken when compared to the other fields that
become green after having received (and lost) focus.
> fix(ember): update dirty-state of identity email field

- docker-compose.yml
- keycloak/config.json
This commit updates the keycloak config. Users in the `admin` group now
have permission to manage users and groups.
Additionally the keycloak config file lost its `dev-` prefix, as it's
also used in prod.
> chore: update keycloak config

- ember/package.json
Otherwise, the dev-server will fail when proxying from HTTP to HTTPS.
> fix(ember): disable secure-proxy for the start-dev NPM run-script.

- ember/app/ui/components/identity-phone-numbers/template.hbs
If there is at least a phone number one must be set as default.
> fix(ember): disallow removing the default flag from phone numbers

- ember/app/ui/components/identity-memberships/component.js
If no timeSlot is set the backend returns null. But Changeset then
fails because it want's to set a property of null.
> fix(ember): add fallback to empty object for timeSlot

- ember/app/ui/components/identity-phone-numbers/component.js
- ember/app/utils/apply-error.js
Add unique handling for phone-numbers and ignore "non-field-errors" in
the utility function.
> fix(ember): update error handling for forms

- ember/app/models/identity.js
- ember/app/ui/components/identity-form/template.hbs
Don't allow setting isOrganisation if it is already member of an
organisation. Don't allor removing isOrganisation if the organisation
has members assigned.
> fix(ember): restrict isOrganisation option in form

- api/mysagw/identity/permissions.py
- api/mysagw/identity/tests/test_address_views.py
- api/mysagw/identity/tests/test_email_views.py
- api/mysagw/identity/tests/test_phone_number_views.py
- api/mysagw/identity/views.py
This commit opens the endpoints for emails, phone_numbers and addresses,
so that users can manage their own data and the data they're authorized
to manage.
> feat(api): let users manage their own data

- api/mysagw/identity/views.py
- ember/app/ui/identities/index/controller.js
- ember/app/ui/identities/index/template.hbs
- ember/translations/en.yaml
This commit an export dropdown instead of button for offering all the
available export types. In this dropdown, the standard export and an
email-only export is available.
Additionally, this commit changes the email export uri path from the api
from `export_email` to `export-email`.
> feat(ember): introduce email-only export

- api/mysagw/identity/filters.py
- api/mysagw/identity/permissions.py
- api/mysagw/identity/tests/test_address_views.py
- api/mysagw/identity/tests/test_email_views.py
- api/mysagw/identity/tests/test_membership_views.py
- api/mysagw/identity/tests/test_phone_number_views.py
- api/mysagw/identity/views.py
Also add `authorized`-filter.
**chore(api): refactor identity permissions**
This commit refactors the permissions for the email, phone and address
views. Additionally, it fixes the parametrisations for certain tests in
order to make sure, the correct permissions are tested.
> feat(api): let users read their own memberships

- api/mysagw/identity/serializers.py
- api/mysagw/identity/tests/test_membership_views.py
- api/mysagw/identity/urls.py
- api/mysagw/identity/views.py
- ember/app/adapters/application.js
- ember/app/adapters/identity.js
- ember/app/ui/profile/index/controller.js
- ember/tests/unit/adapters/application-test.js
- ember/tests/unit/adapters/identity-test.js
Use myorgs serializer for organisation includes on memberships, to
avoid including non public interests
Would this fix the bug or would I break something else with this? Can't remember the originally proposed solution
> fix(api): fix included identity showing private interests

- ember/app/ui/components/submit-button/template.hbs
This is needed, because frontend validation is broken right now.
> chore: temporarily disable frontend validation

- api/mysagw/accounting/queries/get_receipts.gql
- api/mysagw/case/email_texts.py
- api/mysagw/case/serializers.py
- api/mysagw/case/tests/test_case_views.py
- caluma/extensions/common.py
- caluma/extensions/email_texts.py
- caluma/extensions/events/work_item.py
- caluma/extensions/tests/test_events.py
This commit temporarily disables sending of emails for new events and
invitations.
This is needed during the creation of already existing applications.
> chore: temporarily disable mailing

- caluma/Dockerfile
Install sagw-specific deps with `poetry run pip ...` in order to not
upgrade any packages.
> chore: fix caluma

- api/mysagw/identity/filters.py
- api/mysagw/identity/tests/test_identity_views.py
This commit improves the performance of the identity search.
Additionally a small bug was fixed that lead to not displaying all
identities belonging to an organisation.
> fix(api): fix identity search

- .github/dependabot.yml
- ember/package.json
- ember/yarn.lock
upgrade ember-caluma dependencies
change dependabot to ignore certain npm versions
> chore(ember): upgrade dependencies

- ember/app/models/address.js
- ember/app/styles/app.scss
- ember/app/ui/components/identity-addresses/template.hbs
uses similar formatting to the backend identity.address_block
> fix(ember): show more information in address list

- ember/app/ui/application/template.hbs
fix problem with dropdown at the end of the page being cut off
> fix(ember): remove overflow from main content

- caluma/extensions/permissions.py
- ember/app/abilities/case.js
- ember/app/ui/cases/detail/edit/controller.js
- ember/tests/unit/ui/cases/detail/edit/controller-test.js
@open-dynaMIX there was no need for backend changes as the permissions already allow admin and sagw to always edit
The frontend permission are now the same as in the backend
> feat(ember): allow admins to always edit the form

- Makefile
- api/mysagw/oidc_auth/authentication.py
- api/mysagw/oidc_auth/models.py
- api/mysagw/oidc_auth/tests/test_authentication.py
- api/mysagw/settings.py
- caluma/extensions/api_client.py
This commit refactors our authentication backend. There is no need to call the introspection endpoint anymore, which simplifies the implementation by a lot. Additionally, the backend doesn't need to have an oidc client for verifying tokens.
- chore: install pdbpp when running caluma in foreground
> chore: refactor OIDC authentication backend

- docker-compose.yml
With postgresql 14.8, the test
`test_identity_views.py::test_identity_search[admin-SAGW-expected3]` would fail:
```
def _execute(self, sql, params, *ignored_wrapper_args):
self.db.validate_no_broken_transaction()
with self.db.wrap_database_errors:
if params is None:
return self.cursor.execute(sql)
else:
>               return self.cursor.execute(sql, params)
E               django.db.utils.OperationalError: could not load library "/usr/local/lib/postgresql/llvmjit.so": Error relocating /usr/local/lib/postgresql/llvmjit.so: LLVMBuildGEP: symbol not found
/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py:84: OperationalError
```
> chore: pin postgresql to 14.7

- docker-compose.yml
The upstream image was fixed over the weekend. No need to stay on 14.7 anymore.
This reverts commit 06e3c14acdb81a45ab7be0dda5935dd03e671fec.
> Revert: "chore: pin postgresql to 14.7"

- Makefile
- api/mysagw/case/filters.py
- api/mysagw/case/tests/test_case_views.py
- api/mysagw/case/views.py
- ember/app/ui/cases/index/controller.js
- chore(make): use pip in caluma-foreground target
> fix: enforce filter usage for case/accesses endpoint

- ember/app/services/case-data.js
- ember/app/ui/cases/detail/index/controller.js
- ember/app/ui/cases/detail/work-items/edit/form/controller.js
Hitting the cache can result in old data in some cases causing navigation/ buttons to vanish/ display incorrectly
> fix(ember): disable cache for case fetches

- caluma/extensions/visibilities.py
Access is not visible for 60 seconds (cache). We also need to return the WorkItems from cases created by the requesting user.
> fix(caluma): fix visibility for workitem

- api/mysagw/identity/tests/test_membership_views.py
- api/mysagw/identity/views.py
OrganisationAdminMembersViewSet is also used in identity-view, hence the newly introduces restrictions are too strict.
> fix(OrganisationAdminMembersViewSet): extend qs for admins and staff

- api/mysagw/accounting/conftest.py
- api/mysagw/accounting/tests/additional_data_caluma_response.py
- api/mysagw/accounting/tests/test_views.py
- api/mysagw/caluma_document_parser.py
- api/mysagw/case/conftest.py
- api/mysagw/case/tests/test_case_views.py
- api/mysagw/conftest.py
This commit streamlines almost duplicate code in the conftest files of the accounting and case apps into the main conftest file.
- docs: add docstring & fix typo in comment
> chore: refactor mocking in tests that need caluma responses

- README.md
- api/mysagw/case/tests/test_case_views.py
- caluma/extensions/settings.py
- docker-compose.override.yml
The purpose of this commit is to use django-environ for reading environment variables in settings.py. Also an .env file is read from `./caluma/.env` to make it easy to override values in dev. This is especially useful for keycloak client secrets, which can't be set manually.
- chore(api): remove unused snapshot fixture
- chore(caluma): set local UID in dev (same as for API)
> chore(caluma): use environ in settings and also read .env file

- api/mysagw/conftest.py
- api/mysagw/oidc_auth/models.py
- api/mysagw/oidc_auth/tests/test_authentication.py
- api/mysagw/settings.py
- docker-compose.override.yml
- docker-compose.yml
- keycloak/config.json
- next_deployment.md
This commit implements the update of Keycloak to v24.0.4 and configures the user profiles. It also implements the necessary changes in the backend. Additionally all profile fields will be taken from the claims and added to the identities.
> feat: update Keycloak and configure user profiles

- .github/workflows/ghcr.yml
- ember/config/environment.js
Only when Keycloak and frontend are on the same host can relative urls be used.
> ci: build ember in CI

- .pre-commit-config.yaml
- caluma/Dockerfile
- caluma/data/form-config.json
- caluma/extensions/events/__init__.py
- caluma/extensions/events/form.py
- caluma/extensions/settings.py
- caluma/extensions/tests/test_events.py
- caluma/extensions/tests/test_validations.py
- caluma/extensions/validations.py
- docker-compose.yml
This generates a summary of table questions if the table question is configured to do so.
Currently, only a CSV mode is available, but the code is easily extensible to support other summary types as well.
To use it, proceed as follows:
* Create a new (multiline text) question on the form where your table question resides. It will be used to store the summary. Ideally, you should configure it to be hidden.
* Configure the meta attributes of the table question and add the following keys:
- `summary-question`: Slug of the summary question just created above
- `summary-mode`: Calculation mode on how to generate the summary (currently only `"csv"` available)
> feat(form): introduce table summary generator

- Makefile
- api/pyproject.toml
- compose.yaml
- ember/package.json
Drive-by commit: `chore: fix some outdated commands`
> chore: create release for api, frontend and the whole app

- caluma/extensions/events/form.py
- caluma/extensions/tests/test_events.py
This makes sure a newly applied summary config leads to the generation of all the summaries. This has the potential of timing out, if there is a massive amount of Answers. We expect them to be in the lower 100s, so this doesn't justify an async approach.
> feat: also update table summaries on table question change

- api/mysagw/oidc_auth/models.py
- api/mysagw/oidc_auth/tests/test_authentication.py
- ember/app/router.js
- ember/app/services/session.js
- ember/app/ui/support/route.js
- ember/app/ui/support/template.hbs
- ember/translations/support/de.yaml
- ember/translations/support/en.yaml
- ember/translations/support/fr.yaml
This is the first step to resolve this issue. This fix prevents
organisation Identities to be linked with keycloak users. This could
potentially lead to a situation, where a user can make a keycloak
account with their email address, but then be unable to login to mySAGW,
if the Email is already set on an organisation Identity, due to the unique
constraint on the email field.
> fix: do never link users with organisation identities

- api/mysagw/identity/serializers.py
- api/mysagw/identity/tests/test_me_views.py
- ember/app/ui/components/identity-form/template.hbs
This commit makes the main fields of an organisation for organisation admins read-only.
Additionally this fixes two bugs:
1. Fetch title from backend (was always None)
2. Do not display comment field (was always empty)
> feat: prevent org admins from changing fields on the organisation

- ember/app/ui/components/nav-bar/component.js
- ember/app/ui/components/nav-bar/template.hbs
- ember/config/ember-intl.js
- ember/config/environment.js
use our own list of locales as recommended by ember-intl https://ember-intl.github.io/ember-intl/docs/services/intl-part-2#locales
includes small navbar improvements as well
> fix(ember): fix shown locales

- compose.yaml
- ember/app/ui/components/identity-addresses/template.hbs
- ember/app/ui/components/identity-emails/template.hbs
- ember/app/ui/components/identity-form/component.js
- ember/app/ui/components/identity-form/template.hbs
- ember/app/ui/components/identity-interests/template.hbs
- ember/app/ui/components/identity-phone-numbers/template.hbs
- ember/app/ui/profile/edit/template.hbs
- ember/package.json
Fix fields being disabled in too many states.
Remove `readOnlyView` checking, as it is never used
> Fix identity editing

- caluma/extensions/events/case.py
- caluma/extensions/events/work_item.py
- caluma/extensions/settings.py
- caluma/extensions/tests/test_events.py
- ember/translations/documents/de.yaml
- ember/translations/documents/en.yaml
- ember/translations/documents/fr.yaml
- next_deployment.md
Cancelled cases are still accessible via their URL. So the status needs
to be set correctly. This commit adds a new status `canceled` and
sets it on cancelation of a case.
Additionally the event handlers were refactored in the following way:
- only cases with the `document-review` Workflow get a status applied.
- The status is set on every change of ready WorkItems, not only on the
expected forward changes. This makes sure, that the status is also
correct, if a Case was closed and then reopened.
- chore(caluma): fix flaky test
> fix: set status for canceled cases

- caluma/extensions/events/work_item.py
- caluma/extensions/tests/test_events.py
- next_deployment.md
This commit makes sure the status discarded circulations and their workitems is set to `canceled`.
> fix(caluma): Set status of discarded circulations and their work_items
